spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  session:
    store-type: jdbc

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate:
    SQL: debug
    type: TRACE

logging:
  org.hibernate.SQL: debug

server:
  port: 9000
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부